<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYJpJeVi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYJpJeVi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYJpJeVi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYJpJeVi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYJpJeVi\App_KernelDevDebugContainer([
    'container.build_hash' => 'YJpJeVi',
    'container.build_id' => 'd61cd362',
    'container.build_time' => 1581497830,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYJpJeVi');
